#
# Voltus Scheduler command file generated by voltus_rail on Sun Jul 27 11:35:31 2025
#
setvar log_file ./work/voltus_extractor_VDD.log 
setvar output_cache_directory_name /tmp/innovus_temp_1549410_coe-ece-taco_lunayang_ic5TpO/zx_tmp_coe-ece-taco_1907943
setvar library_name ./run1/era_work/incremental_output0/pgv/techonly.cl
setvar output_directory_name ./work
setvar output_file_name VDD 
setvar max_error_messages 100
setvar max_resistor_length 800
setvar hierarchy_char /
layout_file /tmp/innovus_temp_1549410_coe-ece-taco_lunayang_ic5TpO/eps_out_1549410.def.gz
setvar exec_token "/tmp/innovus_temp_1549410_coe-ece-taco_lunayang_ic5TpO/eps_out_1549410.def.gz"
setvar enable_signal_via_overhang false
setvar zx_multinet_extraction false
setvar extraction_mode early
setvar enable_zx_report_shorts true
extraction_type all none
extraction_type pattern {VDD} r_only 
hierarchical_path_tracer netinst_table ./work/VDD.netinst 
hierarchical_path_tracer cell_table ./work/VDD.cellinst 
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
label port VDDvsrc1 111.9300 4.3900 metal10
label port VDDvsrc2 114.4200 129.4450 metal10
label port VDDvsrc3 28.3750 3.8350 metal10
label port VDDvsrc4 28.6500 129.4450 metal10
label port VDDvsrc5 136.5550 103.1650 metal10
label port VDDvsrc6 136.2800 25.1400 metal10
label port VDDvsrc7 4.0850 24.0450 metal10
label port VDDvsrc8 4.0850 96.3600 metal10
hierarchical_path_tracer pgnet_table ./work/all.pgnets
setvar output_def false
setvar cluster_via_size 25
setvar cluster_via1_maximum true
setvar def_merge_supply_shorts false
setvar promote_ports true
setvar max_cpu 1
setvar tech_file gpdk045.tch
setvar density_check_method database
setvar sfedb_path ./work/SFEDB
setvar enable_binary_inst_pgdb true
setvar keep_log_file false
