###################################################################

# Created by write_sdc on Fri Aug 15 19:19:33 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_max_area 0
set_load -pin_load 1.5 [get_ports {result_flat[63]}]
set_load -pin_load 1.5 [get_ports {result_flat[62]}]
set_load -pin_load 1.5 [get_ports {result_flat[61]}]
set_load -pin_load 1.5 [get_ports {result_flat[60]}]
set_load -pin_load 1.5 [get_ports {result_flat[59]}]
set_load -pin_load 1.5 [get_ports {result_flat[58]}]
set_load -pin_load 1.5 [get_ports {result_flat[57]}]
set_load -pin_load 1.5 [get_ports {result_flat[56]}]
set_load -pin_load 1.5 [get_ports {result_flat[55]}]
set_load -pin_load 1.5 [get_ports {result_flat[54]}]
set_load -pin_load 1.5 [get_ports {result_flat[53]}]
set_load -pin_load 1.5 [get_ports {result_flat[52]}]
set_load -pin_load 1.5 [get_ports {result_flat[51]}]
set_load -pin_load 1.5 [get_ports {result_flat[50]}]
set_load -pin_load 1.5 [get_ports {result_flat[49]}]
set_load -pin_load 1.5 [get_ports {result_flat[48]}]
set_load -pin_load 1.5 [get_ports {result_flat[47]}]
set_load -pin_load 1.5 [get_ports {result_flat[46]}]
set_load -pin_load 1.5 [get_ports {result_flat[45]}]
set_load -pin_load 1.5 [get_ports {result_flat[44]}]
set_load -pin_load 1.5 [get_ports {result_flat[43]}]
set_load -pin_load 1.5 [get_ports {result_flat[42]}]
set_load -pin_load 1.5 [get_ports {result_flat[41]}]
set_load -pin_load 1.5 [get_ports {result_flat[40]}]
set_load -pin_load 1.5 [get_ports {result_flat[39]}]
set_load -pin_load 1.5 [get_ports {result_flat[38]}]
set_load -pin_load 1.5 [get_ports {result_flat[37]}]
set_load -pin_load 1.5 [get_ports {result_flat[36]}]
set_load -pin_load 1.5 [get_ports {result_flat[35]}]
set_load -pin_load 1.5 [get_ports {result_flat[34]}]
set_load -pin_load 1.5 [get_ports {result_flat[33]}]
set_load -pin_load 1.5 [get_ports {result_flat[32]}]
set_load -pin_load 1.5 [get_ports {result_flat[31]}]
set_load -pin_load 1.5 [get_ports {result_flat[30]}]
set_load -pin_load 1.5 [get_ports {result_flat[29]}]
set_load -pin_load 1.5 [get_ports {result_flat[28]}]
set_load -pin_load 1.5 [get_ports {result_flat[27]}]
set_load -pin_load 1.5 [get_ports {result_flat[26]}]
set_load -pin_load 1.5 [get_ports {result_flat[25]}]
set_load -pin_load 1.5 [get_ports {result_flat[24]}]
set_load -pin_load 1.5 [get_ports {result_flat[23]}]
set_load -pin_load 1.5 [get_ports {result_flat[22]}]
set_load -pin_load 1.5 [get_ports {result_flat[21]}]
set_load -pin_load 1.5 [get_ports {result_flat[20]}]
set_load -pin_load 1.5 [get_ports {result_flat[19]}]
set_load -pin_load 1.5 [get_ports {result_flat[18]}]
set_load -pin_load 1.5 [get_ports {result_flat[17]}]
set_load -pin_load 1.5 [get_ports {result_flat[16]}]
set_load -pin_load 1.5 [get_ports {result_flat[15]}]
set_load -pin_load 1.5 [get_ports {result_flat[14]}]
set_load -pin_load 1.5 [get_ports {result_flat[13]}]
set_load -pin_load 1.5 [get_ports {result_flat[12]}]
set_load -pin_load 1.5 [get_ports {result_flat[11]}]
set_load -pin_load 1.5 [get_ports {result_flat[10]}]
set_load -pin_load 1.5 [get_ports {result_flat[9]}]
set_load -pin_load 1.5 [get_ports {result_flat[8]}]
set_load -pin_load 1.5 [get_ports {result_flat[7]}]
set_load -pin_load 1.5 [get_ports {result_flat[6]}]
set_load -pin_load 1.5 [get_ports {result_flat[5]}]
set_load -pin_load 1.5 [get_ports {result_flat[4]}]
set_load -pin_load 1.5 [get_ports {result_flat[3]}]
set_load -pin_load 1.5 [get_ports {result_flat[2]}]
set_load -pin_load 1.5 [get_ports {result_flat[1]}]
set_load -pin_load 1.5 [get_ports {result_flat[0]}]
create_clock [get_ports clk]  -period 1.42  -waveform {0 0.71}
set_clock_uncertainty 0.071  [get_clocks clk]
set_input_delay -clock clk  0.0426  [get_ports clk]
set_input_delay -clock clk  0.0426  [get_ports rst_n]
set_input_delay -clock clk  0.0426  [get_ports start]
set_input_delay -clock clk  0.0426  [get_ports preload_valid]
set_input_delay -clock clk  0.0426  [get_ports {preload_addr[3]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_addr[2]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_addr[1]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_addr[0]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_data[7]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_data[6]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_data[5]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_data[4]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_data[3]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_data[2]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_data[1]}]
set_input_delay -clock clk  0.0426  [get_ports {preload_data[0]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[31]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[30]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[29]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[28]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[27]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[26]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[25]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[24]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[23]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[22]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[21]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[20]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[19]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[18]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[17]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[16]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[15]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[14]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[13]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[12]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[11]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[10]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[9]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[8]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[7]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[6]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[5]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[4]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[3]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[2]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[1]}]
set_input_delay -clock clk  0.0426  [get_ports {x_vector_flat[0]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[63]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[62]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[61]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[60]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[59]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[58]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[57]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[56]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[55]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[54]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[53]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[52]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[51]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[50]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[49]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[48]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[47]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[46]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[45]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[44]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[43]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[42]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[41]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[40]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[39]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[38]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[37]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[36]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[35]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[34]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[33]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[32]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[31]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[30]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[29]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[28]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[27]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[26]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[25]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[24]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[23]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[22]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[21]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[20]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[19]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[18]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[17]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[16]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[15]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[14]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[13]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[12]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[11]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[10]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[9]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[8]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[7]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[6]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[5]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[4]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[3]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[2]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[1]}]
set_output_delay -clock clk  0.0568  [get_ports {result_flat[0]}]
