###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID coe-ece-taco)
#  Generated on:      Fri Aug  1 11:45:17 2025
#  Design:            top
#  Command:           create_clock_tree_spec -out_file top.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Common UI
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_db clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_db port:clk .cts_is_sdc_clock_root true

# Clocks present at pin clk
#   clk (period 1.550ns) in timing_config nangate_constraint_mode([top.sdc])
create_clock_tree -name clk -source clk -no_skew_group
# Clock period setting for source pin of clk
set_db port:clk .cts_clock_period 1.55

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_db cts_timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:nangate_constraint_mode (sdc top.sdc)
create_skew_group -name clk/nangate_constraint_mode -sources clk -auto_sinks
set_db skew_group:clk/nangate_constraint_mode .cts_skew_group_include_source_latency true
set_db skew_group:clk/nangate_constraint_mode .cts_skew_group_created_from_clock clk
set_db skew_group:clk/nangate_constraint_mode .cts_skew_group_created_from_constraint_mode nangate_constraint_mode
set_db skew_group:clk/nangate_constraint_mode .cts_skew_group_created_from_delay_corners {nangate_delay_corner_worst nangate_delay_corner_fast}


check_clock_tree_convergence
# Restore the ILM status if possible
if { [get_db ccopt_auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

