###################################################################

# Created by write_sdc on Fri Aug 15 18:30:31 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_max_area 0
set_load -pin_load 1.5 [get_ports {result_flat[127]}]
set_load -pin_load 1.5 [get_ports {result_flat[126]}]
set_load -pin_load 1.5 [get_ports {result_flat[125]}]
set_load -pin_load 1.5 [get_ports {result_flat[124]}]
set_load -pin_load 1.5 [get_ports {result_flat[123]}]
set_load -pin_load 1.5 [get_ports {result_flat[122]}]
set_load -pin_load 1.5 [get_ports {result_flat[121]}]
set_load -pin_load 1.5 [get_ports {result_flat[120]}]
set_load -pin_load 1.5 [get_ports {result_flat[119]}]
set_load -pin_load 1.5 [get_ports {result_flat[118]}]
set_load -pin_load 1.5 [get_ports {result_flat[117]}]
set_load -pin_load 1.5 [get_ports {result_flat[116]}]
set_load -pin_load 1.5 [get_ports {result_flat[115]}]
set_load -pin_load 1.5 [get_ports {result_flat[114]}]
set_load -pin_load 1.5 [get_ports {result_flat[113]}]
set_load -pin_load 1.5 [get_ports {result_flat[112]}]
set_load -pin_load 1.5 [get_ports {result_flat[111]}]
set_load -pin_load 1.5 [get_ports {result_flat[110]}]
set_load -pin_load 1.5 [get_ports {result_flat[109]}]
set_load -pin_load 1.5 [get_ports {result_flat[108]}]
set_load -pin_load 1.5 [get_ports {result_flat[107]}]
set_load -pin_load 1.5 [get_ports {result_flat[106]}]
set_load -pin_load 1.5 [get_ports {result_flat[105]}]
set_load -pin_load 1.5 [get_ports {result_flat[104]}]
set_load -pin_load 1.5 [get_ports {result_flat[103]}]
set_load -pin_load 1.5 [get_ports {result_flat[102]}]
set_load -pin_load 1.5 [get_ports {result_flat[101]}]
set_load -pin_load 1.5 [get_ports {result_flat[100]}]
set_load -pin_load 1.5 [get_ports {result_flat[99]}]
set_load -pin_load 1.5 [get_ports {result_flat[98]}]
set_load -pin_load 1.5 [get_ports {result_flat[97]}]
set_load -pin_load 1.5 [get_ports {result_flat[96]}]
set_load -pin_load 1.5 [get_ports {result_flat[95]}]
set_load -pin_load 1.5 [get_ports {result_flat[94]}]
set_load -pin_load 1.5 [get_ports {result_flat[93]}]
set_load -pin_load 1.5 [get_ports {result_flat[92]}]
set_load -pin_load 1.5 [get_ports {result_flat[91]}]
set_load -pin_load 1.5 [get_ports {result_flat[90]}]
set_load -pin_load 1.5 [get_ports {result_flat[89]}]
set_load -pin_load 1.5 [get_ports {result_flat[88]}]
set_load -pin_load 1.5 [get_ports {result_flat[87]}]
set_load -pin_load 1.5 [get_ports {result_flat[86]}]
set_load -pin_load 1.5 [get_ports {result_flat[85]}]
set_load -pin_load 1.5 [get_ports {result_flat[84]}]
set_load -pin_load 1.5 [get_ports {result_flat[83]}]
set_load -pin_load 1.5 [get_ports {result_flat[82]}]
set_load -pin_load 1.5 [get_ports {result_flat[81]}]
set_load -pin_load 1.5 [get_ports {result_flat[80]}]
set_load -pin_load 1.5 [get_ports {result_flat[79]}]
set_load -pin_load 1.5 [get_ports {result_flat[78]}]
set_load -pin_load 1.5 [get_ports {result_flat[77]}]
set_load -pin_load 1.5 [get_ports {result_flat[76]}]
set_load -pin_load 1.5 [get_ports {result_flat[75]}]
set_load -pin_load 1.5 [get_ports {result_flat[74]}]
set_load -pin_load 1.5 [get_ports {result_flat[73]}]
set_load -pin_load 1.5 [get_ports {result_flat[72]}]
set_load -pin_load 1.5 [get_ports {result_flat[71]}]
set_load -pin_load 1.5 [get_ports {result_flat[70]}]
set_load -pin_load 1.5 [get_ports {result_flat[69]}]
set_load -pin_load 1.5 [get_ports {result_flat[68]}]
set_load -pin_load 1.5 [get_ports {result_flat[67]}]
set_load -pin_load 1.5 [get_ports {result_flat[66]}]
set_load -pin_load 1.5 [get_ports {result_flat[65]}]
set_load -pin_load 1.5 [get_ports {result_flat[64]}]
set_load -pin_load 1.5 [get_ports {result_flat[63]}]
set_load -pin_load 1.5 [get_ports {result_flat[62]}]
set_load -pin_load 1.5 [get_ports {result_flat[61]}]
set_load -pin_load 1.5 [get_ports {result_flat[60]}]
set_load -pin_load 1.5 [get_ports {result_flat[59]}]
set_load -pin_load 1.5 [get_ports {result_flat[58]}]
set_load -pin_load 1.5 [get_ports {result_flat[57]}]
set_load -pin_load 1.5 [get_ports {result_flat[56]}]
set_load -pin_load 1.5 [get_ports {result_flat[55]}]
set_load -pin_load 1.5 [get_ports {result_flat[54]}]
set_load -pin_load 1.5 [get_ports {result_flat[53]}]
set_load -pin_load 1.5 [get_ports {result_flat[52]}]
set_load -pin_load 1.5 [get_ports {result_flat[51]}]
set_load -pin_load 1.5 [get_ports {result_flat[50]}]
set_load -pin_load 1.5 [get_ports {result_flat[49]}]
set_load -pin_load 1.5 [get_ports {result_flat[48]}]
set_load -pin_load 1.5 [get_ports {result_flat[47]}]
set_load -pin_load 1.5 [get_ports {result_flat[46]}]
set_load -pin_load 1.5 [get_ports {result_flat[45]}]
set_load -pin_load 1.5 [get_ports {result_flat[44]}]
set_load -pin_load 1.5 [get_ports {result_flat[43]}]
set_load -pin_load 1.5 [get_ports {result_flat[42]}]
set_load -pin_load 1.5 [get_ports {result_flat[41]}]
set_load -pin_load 1.5 [get_ports {result_flat[40]}]
set_load -pin_load 1.5 [get_ports {result_flat[39]}]
set_load -pin_load 1.5 [get_ports {result_flat[38]}]
set_load -pin_load 1.5 [get_ports {result_flat[37]}]
set_load -pin_load 1.5 [get_ports {result_flat[36]}]
set_load -pin_load 1.5 [get_ports {result_flat[35]}]
set_load -pin_load 1.5 [get_ports {result_flat[34]}]
set_load -pin_load 1.5 [get_ports {result_flat[33]}]
set_load -pin_load 1.5 [get_ports {result_flat[32]}]
set_load -pin_load 1.5 [get_ports {result_flat[31]}]
set_load -pin_load 1.5 [get_ports {result_flat[30]}]
set_load -pin_load 1.5 [get_ports {result_flat[29]}]
set_load -pin_load 1.5 [get_ports {result_flat[28]}]
set_load -pin_load 1.5 [get_ports {result_flat[27]}]
set_load -pin_load 1.5 [get_ports {result_flat[26]}]
set_load -pin_load 1.5 [get_ports {result_flat[25]}]
set_load -pin_load 1.5 [get_ports {result_flat[24]}]
set_load -pin_load 1.5 [get_ports {result_flat[23]}]
set_load -pin_load 1.5 [get_ports {result_flat[22]}]
set_load -pin_load 1.5 [get_ports {result_flat[21]}]
set_load -pin_load 1.5 [get_ports {result_flat[20]}]
set_load -pin_load 1.5 [get_ports {result_flat[19]}]
set_load -pin_load 1.5 [get_ports {result_flat[18]}]
set_load -pin_load 1.5 [get_ports {result_flat[17]}]
set_load -pin_load 1.5 [get_ports {result_flat[16]}]
set_load -pin_load 1.5 [get_ports {result_flat[15]}]
set_load -pin_load 1.5 [get_ports {result_flat[14]}]
set_load -pin_load 1.5 [get_ports {result_flat[13]}]
set_load -pin_load 1.5 [get_ports {result_flat[12]}]
set_load -pin_load 1.5 [get_ports {result_flat[11]}]
set_load -pin_load 1.5 [get_ports {result_flat[10]}]
set_load -pin_load 1.5 [get_ports {result_flat[9]}]
set_load -pin_load 1.5 [get_ports {result_flat[8]}]
set_load -pin_load 1.5 [get_ports {result_flat[7]}]
set_load -pin_load 1.5 [get_ports {result_flat[6]}]
set_load -pin_load 1.5 [get_ports {result_flat[5]}]
set_load -pin_load 1.5 [get_ports {result_flat[4]}]
set_load -pin_load 1.5 [get_ports {result_flat[3]}]
set_load -pin_load 1.5 [get_ports {result_flat[2]}]
set_load -pin_load 1.5 [get_ports {result_flat[1]}]
set_load -pin_load 1.5 [get_ports {result_flat[0]}]
create_clock [get_ports clk]  -period 1.48  -waveform {0 0.74}
set_clock_uncertainty 0.074  [get_clocks clk]
set_input_delay -clock clk  0.0444  [get_ports clk]
set_input_delay -clock clk  0.0444  [get_ports rst_n]
set_input_delay -clock clk  0.0444  [get_ports start]
set_input_delay -clock clk  0.0444  [get_ports preload_valid]
set_input_delay -clock clk  0.0444  [get_ports {preload_addr[5]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_addr[4]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_addr[3]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_addr[2]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_addr[1]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_addr[0]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_data[7]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_data[6]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_data[5]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_data[4]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_data[3]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_data[2]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_data[1]}]
set_input_delay -clock clk  0.0444  [get_ports {preload_data[0]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[63]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[62]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[61]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[60]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[59]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[58]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[57]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[56]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[55]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[54]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[53]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[52]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[51]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[50]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[49]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[48]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[47]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[46]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[45]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[44]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[43]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[42]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[41]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[40]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[39]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[38]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[37]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[36]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[35]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[34]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[33]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[32]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[31]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[30]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[29]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[28]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[27]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[26]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[25]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[24]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[23]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[22]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[21]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[20]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[19]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[18]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[17]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[16]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[15]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[14]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[13]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[12]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[11]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[10]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[9]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[8]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[7]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[6]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[5]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[4]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[3]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[2]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[1]}]
set_input_delay -clock clk  0.0444  [get_ports {x_vector_flat[0]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[127]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[126]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[125]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[124]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[123]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[122]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[121]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[120]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[119]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[118]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[117]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[116]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[115]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[114]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[113]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[112]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[111]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[110]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[109]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[108]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[107]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[106]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[105]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[104]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[103]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[102]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[101]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[100]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[99]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[98]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[97]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[96]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[95]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[94]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[93]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[92]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[91]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[90]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[89]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[88]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[87]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[86]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[85]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[84]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[83]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[82]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[81]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[80]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[79]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[78]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[77]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[76]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[75]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[74]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[73]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[72]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[71]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[70]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[69]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[68]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[67]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[66]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[65]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[64]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[63]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[62]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[61]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[60]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[59]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[58]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[57]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[56]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[55]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[54]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[53]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[52]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[51]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[50]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[49]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[48]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[47]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[46]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[45]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[44]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[43]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[42]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[41]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[40]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[39]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[38]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[37]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[36]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[35]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[34]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[33]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[32]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[31]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[30]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[29]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[28]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[27]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[26]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[25]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[24]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[23]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[22]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[21]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[20]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[19]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[18]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[17]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[16]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[15]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[14]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[13]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[12]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[11]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[10]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[9]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[8]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[7]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[6]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[5]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[4]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[3]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[2]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[1]}]
set_output_delay -clock clk  0.0592  [get_ports {result_flat[0]}]
